site_name: girder-pytest-pyppeteer
theme:
  name: material
plugins:
  - mkdocstrings

nav:
  - Home: 'index.md'
  - Components:
    - 'pytest_plugin.md'
    - 'github_action.md'
  - 'setup.md'
  - Debugging: 'debugging.md'