name: Build docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: pytest-pyppeteer

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker image
        run: docker build . --file pyppeteer.Dockerfile --tag ghcr.io/dchiquito/$IMAGE_NAME:latest
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Upload the docker image to GitHub Container Registry
        run: docker push ghcr.io/dchiquito/$IMAGE_NAME:latest