name: Build docker image

on:
  release:
    types: [published] # use `published` instead of `created` b/c `created` also runs on draft releases

env:
  IMAGE_NAME: pytest-pyppeteer

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker image
        run: docker build . --file pyppeteer.Dockerfile --tag ghcr.io/girder/$IMAGE_NAME:latest
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Upload the docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/girder/$IMAGE_NAME:latest
          echo $GITHUB_REF
          echo $GITHUB_REF_NAME
          docker push ghcr.io/girder/$IMAGE_NAME:$GITHUB_REF_NAME
